name: java-ref-plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types:
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: 6.x

      - name: Execute GitVersion
        uses: gittools/actions/gitversion/execute@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build and test
        env:
          ORG_GRADLE_PROJECT_version: $(GitVersion_FullSemVer)
        run: ./gradlew build

      - name: Upload Gradle build output
        uses: actions/upload-artifact@v5
        with:
          name: gradle-build-output
          path: build/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Download Gradle build output
        uses: actions/download-artifact@v4
        with:
          name: gradle-build-output
          path: .

      - name: Publish release to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ORG_GRADLE_PROJECT_version: $(GitVersion_FullSemVer)
        run: >
          ./gradlew publish
          -x compileJava
          -x compileTestJava
          -x processResources
          -x processTestResources
          -x classes
          -x testClasses
          -x jar
          -x sourcesJar
          -x test
